export const WINDOW_TITLE_JOKES = [
    "sudo make me a sandwich",
    "rm -rf / --no-preserve-root",
    "404: Sleep Not Found",
    "git push --force",
    "Compiling...",
    "I'm feeling lucky",
    "ping 8.8.8.8",
    "Searching for meaning...",
    "System.out.println('Hello')",
    "C:\\DOS\\RUN",
    "Namaste",
    "Searching for WiFi...",
    "Insert disk 2 to continue",
    "Press ANY key to panic",
    "Guru Meditation",
    "PC Load Letter",
    "It works on my machine",
    "git commit -m 'fixed stuff'",
    "chmod 777 universe",
    "while(true) { sleep(); }",
    "Ctrl+Alt+Del in progress",
    "Identifying identity...",
    "Downloading RAM...",
    "Hacking the mainframe...",
    "Establish connection...",
    "rm -rf /past/mistakes",
    "Defragmenting reality...",
    "A fatal exception has occurred",
    "Task failed successfully",
    "Reticulating splines...",
    "Buffer overflow...",
    "Blue Screen of Life",
    "Formatting C: ...",
    "Kernel panic!",
    "Undefined is not a function",
    "00101010"
];
